#!/usr/bin/bash

DIR=${DIR:-certs}
ACC_CSR_JSON=service-account-csr.json
ACC_CSR=$DIR/$ACC_CSR_JSON
cat > $ACC_CSR <<EOF
{
  "CN": "service-accounts",
  "key": {
    "algo": "rsa",
    "size": 2048
  },
  "names": [
    {
      "C": "US",
      "L": "Portland",
      "O": "Kubernetes",
      "OU": "Kubernetes The Hard Way",
      "ST": "Oregon"
    }
  ]
}
EOF

$(cd $DIR; cfssl gencert \
  -ca=ca.pem \
  -ca-key=ca-key.pem \
  -config=ca-config.json \
  -profile=kubernetes \
  $ACC_CSR_JSON | cfssljson -bare service-account)

