#!/usr/bin/bash

DIR=${DIR:-certs}
SCHED_CSR_JSON=kube-scheduler-csr.json
SCHED_CSR=$DIR/$SCHED_CSR_JSON

cat > $SCHED_CSR <<EOF
{
  "CN": "system:kube-scheduler",
  "key": {
    "algo": "rsa",
    "size": 2048
  },
  "names": [
    {
      "C": "US",
      "L": "Portland",
      "O": "system:kube-scheduler",
      "OU": "Kubernetes The Hard Way",
      "ST": "Oregon"
    }
  ]
}
EOF

$(cd $DIR; cfssl gencert \
  -ca=ca.pem \
  -ca-key=ca-key.pem \
  -config=ca-config.json \
  -profile=kubernetes \
  $SCHED_CSR_JSON | cfssljson -bare kube-scheduler)

