#!/usr/bin/bash

DIR=${DIR:-certs}
K8S_CSR_JSON=kubernetes-csr.json
K8S_CSR=$DIR/$K8S_CSR_JSON

cat > $K8S_CSR <<EOF
{
  "CN": "kubernetes",
  "key": {
    "algo": "rsa",
    "size": 2048
  },
  "names": [
    {
      "C": "US",
      "L": "Portland",
      "O": "Kubernetes",
      "OU": "Kubernetes The Hard Way",
      "ST": "Oregon"
    }
  ]
}
EOF

$(cd $DIR; cfssl gencert \
  -ca=ca.pem \
  -ca-key=ca-key.pem \
  -config=ca-config.json \
  -hostname=10.32.0.1,10.240.0.10,10.240.0.11,10.240.0.12,10.240.0.13,127.0.0.1,kubernetes.default \
  -profile=kubernetes \
  $K8S_CSR_JSON | cfssljson -bare kubernetes)
