#!/usr/bin/bash
DIR=${DIR:-certs}
PROXY_CSR_JSON=kube-proxy-csr.json
PROXY_CSR=$DIR/$PROXY_CSR_JSON

cat > $PROXY_CSR <<EOF
{
  "CN": "system:kube-proxy",
  "key": {
    "algo": "rsa",
    "size": 2048
  },
  "names": [
    {
      "C": "US",
      "L": "Portland",
      "O": "system:node-proxier",
      "OU": "Kubernetes The Hard Way",
      "ST": "Oregon"
    }
  ]
}
EOF

$(cd $DIR; cfssl gencert \
  -ca=ca.pem \
  -ca-key=ca-key.pem \
  -config=ca-config.json \
  -profile=kubernetes \
  $PROXY_CSR_JSON | cfssljson -bare kube-proxy)
