#!/usr/bin/bash

DIR=${DIR:-certs}
ADMIN_CSR_JSON=admin-csr.json
ADMIN_CSR=$DIR/$ADMIN_CSR_JSON

cat > $ADMIN_CSR <<EOF
{
  "CN": "admin",
  "key": {
    "algo": "rsa",
    "size": 2048
  },
  "names": [
    {
      "C": "US",
      "L": "Portland",
      "O": "system:masters",
      "OU": "Kubernetes The Hard Way",
      "ST": "Oregon"
    }
  ]
}
EOF

$(cd $DIR; cfssl gencert \
  -ca=ca.pem \
  -ca-key=ca-key.pem \
  -config=ca-config.json \
  -profile=kubernetes \
  $ADMIN_CSR_JSON | cfssljson -bare admin)


