#!/usr/bin/bash
DIR=${DIR:-certs}

MNGR_CSR_JSON=kube-controller-manager-csr.json
MNGR_CSR=$DIR/$MNGR_CSR_JSON

cat > $MNGR_CSR  <<EOF
{
  "CN": "system:kube-controller-manager",
  "key": {
    "algo": "rsa",
    "size": 2048
  },
  "names": [
    {
      "C": "US",
      "L": "Portland",
      "O": "system:kube-controller-manager",
      "OU": "Kubernetes The Hard Way",
      "ST": "Oregon"
    }
  ]
}
EOF

$(cd $DIR; cfssl gencert \
  -ca=ca.pem \
  -ca-key=ca-key.pem \
  -config=ca-config.json \
  -profile=kubernetes \
  $MNGR_CSR_JSON | cfssljson -bare kube-controller-manager)
