#!/usr/bin/bash

set -e 

PKI="../pki/certs"

kubectl config set-cluster kubernetes-the-hard-way \
  --certificate-authority=${PKI}/ca.pem \
  --embed-certs=true \
  --server=https://127.0.0.1:6443 \
  --kubeconfig=configs/kube-scheduler.kubeconfig

kubectl config set-credentials system:kube-scheduler \
  --client-certificate=${PKI}/kube-scheduler.pem \
  --client-key=${PKI}/kube-scheduler-key.pem \
  --embed-certs=true \
  --kubeconfig=configs/kube-scheduler.kubeconfig

kubectl config set-context default \
  --cluster=kubernetes-the-hard-way \
  --user=system:kube-scheduler \
  --kubeconfig=configs/kube-scheduler.kubeconfig

kubectl config use-context default --kubeconfig=configs/kube-scheduler.kubeconfig
