#!/usr/bin/bash

set -e

KUBERNETES_LB_ADDRESS=$(drill lb-0.kubernetes -Q)
CLUSTER_NAME=kubernetes-the-hard-way
PKI="../pki/certs"

for instance in worker-0 worker-1 worker-2; do

  kubectl config set-cluster ${CLUSTER_NAME} \
    --certificate-authority=${PKI}/ca.pem \
    --embed-certs=true \
    --server=https://${KUBERNETES_LB_ADDRESS}:6443 \
    --kubeconfig=configs/${instance}.kubeconfig

  kubectl config set-credentials system:node:${instance} \
    --client-certificate=${PKI}/${instance}.pem \
    --client-key=${PKI}/${instance}-key.pem \
    --embed-certs=true \
    --kubeconfig=configs/${instance}.kubeconfig

  kubectl config set-context default \
    --cluster=kubernetes-the-hard-way \
    --user=system:node:${instance} \
    --kubeconfig=configs/${instance}.kubeconfig

  kubectl config use-context default --kubeconfig=configs/${instance}.kubeconfig
done



