- name: Config files for the controllers
  hosts: controller
  tasks:
    - name: copy kubernetes.pem
      copy:
        src: "{{ item }}"
        dest: ~/
        owner: leon
        group: wheel
        mode: 0644
      loop:
        - /home/leon/dev/k8s-learing/pki/certs/kubernetes.pem
        - /home/leon/dev/k8s-learing/pki/certs/kubernetes-key.pem
        - /home/leon/dev/k8s-learing/pki/certs/ca-key.pem
        - /home/leon/dev/k8s-learing/pki/certs/ca.pem
        - /home/leon/dev/k8s-learing/pki/certs/service-account-key.pem
        - /home/leon/dev/k8s-learing/pki/certs/service-account.pem
        - /home/leon/dev/k8s-learing/k8s-config/configs/admin.kubeconfig
        - /home/leon/dev/k8s-learing/k8s-config/configs/kube-controller-manager.kubeconfig
        - /home/leon/dev/k8s-learing/k8s-config/configs/kube-scheduler.kubeconfig
        - /home/leon/dev/k8s-learing/k8s-config/static/kube-scheduler.yaml
        - /home/leon/dev/k8s-learing/k8s-config/static/rbac.yaml
        - /home/leon/dev/k8s-learing/data-encryption-config/encryption-config.yaml
