- name: Bootstrap etcd
  hosts: controller
  tasks:
    # - name: Download
    #   become: yes
    #   become_method: sudo
    #   get_url:
    #     url: "{{ item }}"
    #     dest: /usr/local/bin
    #     mode: +x
    #   with_items:
    #     - https://storage.googleapis.com/kubernetes-release/release/v1.12.0/bin/linux/amd64/kube-apiserver
    #     - https://storage.googleapis.com/kubernetes-release/release/v1.12.0/bin/linux/amd64/kube-controller-manager
    #     - https://storage.googleapis.com/kubernetes-release/release/v1.12.0/bin/linux/amd64/kube-scheduler
    #     - https://storage.googleapis.com/kubernetes-release/release/v1.12.0/bin/linux/amd64/kubectl
    - name: create directories
      become: yes
      become_method: sudo
      file:
        state: directory
        path: "{{ item }}"
      with_items:
        - /etc/kubernetes/config/
        - /var/lib/kubernetes/
    - name: copy files
      become: yes
      become_method: sudo
      copy:
        src: /home/leon/{{ item }}
        dest: /var/lib/kubernetes/{{ item }}
        remote_src: yes
      with_items:
        - ca.pem
        - ca-key.pem
        - kubernetes.pem
        - kubernetes-key.pem
        - encryption-config.yaml
        - service-account.pem
        - service-account-key.pem
        - kube-controller-manager.kubeconfig
        - kube-scheduler.kubeconfig
    - name: copy files
      become: yes
      become_method: sudo
      copy:
        src: /home/leon/{{ item }}
        dest: /etc/kubernetes/config/{{ item }}
        remote_src: yes
      with_items:
        - kube-scheduler.yaml

    - name: Copy Systemd files 
      become: yes
      become_method: sudo
      template: 
        src: template/{{ item }}.service.j2
        dest: /etc/systemd/system/{{ item }}.service
      with_items:
        - kube-api
        - kube-controller-manager
        - kube-scheduler
    - name: Enable and start the kubernetes services
      become: yes
      become_method: sudo
      systemd:
        name: "{{ item }}"
        daemon_reload: yes
        enabled: yes
        state: started
      with_items:
        - kube-api
        - kube-controller-manager
        - kube-scheduler
