- name: Bootstrap the load balancer
  hosts: load-balancer
  tasks:
    - name: Install haproxy
      become: true
      become_user: root
      package:
        name:
          - haproxy
    - name: copy haproxy.cfg
      ansible.builtin.copy:
        src: "{{ item }}" 
        dest: ~/
        owner: leon
        group: wheel
        mode: 0644
      with_items:
        - /home/leon/dev/k8s-learing/k8s-config/static/haproxy.cfg
    - name: Enable and re-start haproxy
      become: yes
      become_method: sudo
      systemd:
        name: haproxy
        enabled: yes
        state: restarted

