- name: CA configuration worker
  hosts: workers
  tasks:
    - name: copy worker keys
      ansible.builtin.copy:
        src: /home/leon/dev/k8s-learing/pki/{{ inventory_hostname|replace('.kubernetes','') }}-key.pem
        dest: ~/
        owner: leon
        group: wheel
        mode: 0644
    - name: copy worker certs
      ansible.builtin.copy:
        src: /home/leon/dev/k8s-learing/pki/{{ inventory_hostname|replace('.kubernetes','') }}.pem
        dest: ~/
        owner: leon
        group: wheel
        mode: 0644
    - name: copy CA to worker
      ansible.builtin.copy:
        src: /home/leon/dev/k8s-learing/pki/ca.pem
        dest: ~/
        owner: leon
        group: wheel
        mode: 0644
    - name: worker kubeconfig
      ansible.builtin.copy:
        src: /home/leon/dev/k8s-learing/k8s-config/{{ inventory_hostname|replace('.kubernetes','') }}.kubeconfig
        dest: ~/
        owner: leon
        group: wheel
        mode: 0644


- name: CA configuration controller
  hosts: controller
  tasks:
    - name: copy kubernetes.pem
      ansible.builtin.copy:
        src: /home/leon/dev/k8s-learing/pki/kubernetes.pem
        dest: ~/
        owner: leon
        group: wheel
        mode: 0644
    - name: copy kubernetes-key.pem
      ansible.builtin.copy:
        src: /home/leon/dev/k8s-learing/pki/kubernetes-key.pem
        dest: ~/
        owner: leon
        group: wheel
        mode: 0644
    - name: copy ca-key
      ansible.builtin.copy:
        src: /home/leon/dev/k8s-learing/pki/ca-key.pem
        dest: ~/
        owner: leon
        group: wheel
        mode: 0644
    - name: copy ca
      ansible.builtin.copy:
        src: /home/leon/dev/k8s-learing/pki/ca.pem
        dest: ~/
        owner: leon
        group: wheel
        mode: 0644
    - name: copy controller service account key
      ansible.builtin.copy:
        src: /home/leon/dev/k8s-learing/pki/service-account-key.pem
        dest: ~/
        owner: leon
        group: wheel
        mode: 0644
    - name: copy controller service account cert
      ansible.builtin.copy:
        src: /home/leon/dev/k8s-learing/pki/service-account.pem
        dest: ~/
        owner: leon
        group: wheel
        mode: 0644
    - name: copy admin.kubeconfig
      ansible.builtin.copy:
        src: /home/leon/dev/k8s-learing/k8s-config/admin.kubeconfig
        dest: ~/
        owner: leon
        group: wheel
        mode: 0644
    - name: copy kube-controller-manager.kubeconfig
      ansible.builtin.copy:
        src: /home/leon/dev/k8s-learing/k8s-config/kube-controller-manager.kubeconfig
        dest: ~/
        owner: leon
        group: wheel
        mode: 0644
    - name: copy kube-scheduler.kubeconfig
      ansible.builtin.copy:
        src: /home/leon/dev/k8s-learing/k8s-config/kube-scheduler.kubeconfig
        dest: ~/
        owner: leon
        group: wheel
        mode: 0644
    - name: Copy Data Encryption Config
      ansible.builtin.copy:
        src: /home/leon/dev/k8s-learing/data-encryption-config/encryption-config.yaml
        dest: ~/
        owner: leon
        group: wheel
        mode: 0644
